### ISSUE TITLE
Incompatibility with avalanchego v1.11.10 (rpc version 36)

### ISSUE THREAD

**Issue by Chris-Sheridan** [ava-labs/subnet-evm#1249]
**Describe the bug**
It appears that avalanchego was upgraded today to v1.11.10 which included an RPC version uptick to 36.

**To Reproduce**
When I try to config/deploy a new subnet locally, I receive the error "Error: the current avalanchego deployment uses rpc version 36 but your subnet has version 35 and is not compatible".

**Expected behavior**
A subnet is configured and deployed successfully.

**Additional context**
Apologies if this is the wrong forum.  I've tried downgrading my avalanchego to 1.11.9, but the system keeps updating itself back to 1.11.10 and I'm blocked.  I appreciate someone sharing if I am missing something on my end.  Thanks!

**Comment by PaTiToMaSteR** [comment]
ok rolling back, @ceyonur I don't know what system force you and the team to release version after version of AvalancheGo without its corresponding subnet-evm. Doesn't make any sense, your LATEST version in your repositories are not working together leaving your main branch broken instead of being the most stable.

@Chris-Sheridan thanks for the report. I'm hitting the same issue. And yes, developers we need the latest version of all plenty of times, not only thinking in production team.
