### ISSUE TITLE
Allow subnet-evm to move forward with upgrade.json retroactively

### ISSUE THREAD

**Issue by yulin-dong** [ava-labs/subnet-evm#254]
Currently, if a subnet-evm node misses an upgrade.json, it will not be allowed to move forward. 

We should provide a way to allow subnet owner to move forward instead.

Related code: https://github.com/ava-labs/subnet-evm/blob/9711be81dd7dd811deec0394a1b4f4db6986f3c6/params/precompile_config.go#L275-L284

**Comment by ceyonur** [comment]
We have discussed this with @aaronbuchwald and we can either forcefully disable checks or use last accepted block instead of the header block in these checks.

**Comment by aaronbuchwald** [comment]
We should just use the last accepted block instead of the head block for this check here.

For precompile upgrades, there is a change in the state when the precompile activates, so as long as this is one node that is getting left behind the rest of the network, such that the rest of the network moves forward with the precompile upgrade and the node left behind cannot make progress to accept a block without the upgrade, then its last accepted block will necessarily be behind the activation timestamp.

If the node has accepted a block after the precompile upgrade activation timestamp, then it would need to revert an accepted block to retro-actively apply the upgrade.

Note: for non-precompile network upgrades that change the rules of execution, but do not necessarily impact the result of every block this may not be the case.

The only case where a flag to override this check would provide a difference in behavior from that is if they are applying a network upgrade that does not change the execution of every block (ie. non-precompile network upgrade) and the node has already accepted blocks past the timestamp of this network upgrade. These network upgrades will be much less frequent, and adding a config flag to override this would be more likely to cause problems than help.
