### ISSUE TITLE
Add Requirement that SubnetEVM Upgrade is Enabled

### ISSUE THREAD

**Issue by aaronbuchwald** [ava-labs/subnet-evm#264]
We should add a requirement that the SubnetEVM upgrade is enabled so that we can deprecate support for it being disabled. It should always be enabled from genesis.

**Comment by anusha-ctrl** [comment]
Look at all places IsSubnetEVM is enabled and force genesis to have it

**Comment by anusha-ctrl** [comment]
Hey, updated the priority on this ticket to urgent: https://github.com/ava-labs/subnet-evm/issues/264 because of the fee reward manager bug. We want to make sure that everyone is running the code we expect them to and if anyone launches an important subnet that violates this, then we will no longer be able to make this change. Could you put up a couple line PR today that will enforce this within vm.Initialize(...) ? It should simply return an error if the fork is not enabled in the genesis and we can separately remove all of the places where we use .IsSubnetEVM to change behavior later
