### ISSUE TITLE
network runner doesn't work with 1 node

### ISSUE THREAD

**Issue by shubhamgoyal42** [ava-labs/subnet-evm#385]
**Describe the bug**
The network doesn't work with 1 node.  It works with the number of nodes >= 4, but not with nodes < 4.
**To Reproduce**
Change [WithNumNodes](https://github.com/ava-labs/subnet-evm/blob/master/tests/e2e/e2e_test.go#L175 ) to 1, and run using scripts/run.sh

**Expected behavior**
The network should work with 1 node.

**Screenshots**
<img width="778" alt="Screenshot 2022-12-01 at 12 24 07 PM" src="https://user-images.githubusercontent.com/22051142/204985714-786bd38c-766d-47b7-8240-363a9bf00f5f.png">
<img width="1235" alt="Screenshot 2022-12-01 at 12 28 19 PM" src="https://user-images.githubusercontent.com/22051142/204986404-b62bdf27-7d3b-4cd2-8275-b9ad926119b1.png">

**Logs**
https://pastebin.com/ZbMuSJNz

**Operating System**
MacOS Ventura 13.0.1

**Additional context**
Avalanchego version 1.9.2, network runner version 35be10cd3867a94fbe960a1c14a455f179de60d9

**Comment by aaronbuchwald** [comment]
This is an issue with the network runner: https://github.com/ava-labs/avalanche-network-runner, although it's not so much a bug in the network runner as how it's being used here.

The standard genesis of the network includes 5 validators and so if you start the network with only one only 1 of the 5 validator nodes will be online, such that there will not be a sufficient portion of stake online. To run a single node network, you will need to modify the genesis so that it creates a network with a single node.
