### ISSUE TITLE
Question: how to setup your own token for gas fee in a subnet-evm

### ISSUE THREAD

**Issue by DDiscua** [ava-labs/subnet-evm#437]
Hi guys, 

I was checking the Avalanche Documentation  : https://support.avax.network/en/articles/6158840-subnet-faq

**Can we use any token on our Subnet?**

Yes, you can choose to use any token as your native token. 

How can I set my own TOKEN as native token and then set this token for the gas?

Let's suppose that I have a WRAPPED XYZ Token and want to configure as my native token of a subnet? 

I haven't found a way to do this.

**Comment by aaronbuchwald** [comment]
Hey @DDiscua , when you create a blockchain with Subnet-EVM, you can specify the genesis of that blockchain with an arbitrary amount of the native coin on that network. Additionally, the VM itself governs the rules for how that native coin can be minted, burned, or transferred.

In order to use your own token as the native coin of a blockchain running Subnet-EVM, you need to set up a system for that token to be bridged to and from Subnet-EVM.

For example, if you have a token on the C-Chain, you could create a lock and mint bridge that allowed those funds to be moved to Subnet-EVM and allow the bridging contract to mint more of the native coin when it receives bridged funds. To move them back, the same bridging contract would then want to burn those funds before releasing them on the C-Chain.

The community wrote up an example of this, which is included in the docs here: https://docs.avax.network/community/tutorials-contest/2022/erc20-as-subnet-gas-token#create-the-relayer-application.

After integrating Avalanche Warp Messaging, we will put together more documentation on best practices of how you can achieve this.
