### ISSUE TITLE
Precompile to override / implement validator rewards formula (and adjust APY)

### ISSUE THREAD

**Issue by gatesyp** [ava-labs/subnet-evm#455]
**Context and scope**
The mainnet rewards calculations are here: 
https://github.com/ava-labs/avalanchego/blob/master/vms/platformvm/reward/calculator.go#L40
with the genesis config defined here:
https://github.com/ava-labs/avalanchego/blob/master/genesis/genesis_mainnet.go#L35

In my mind, it'd be awesome to have an easy interface (precompile?) to initialize / override the reward formula used for my `subnet-evm`, and effectively adjust a validator's APY. 

What/where is the `subnet-evm`'s equivalent of this?

**Comment by ceyonur** [comment]
Staking operations happen on the P-Chain, subnet-evm does not have any native-staking mechanism. With Banff we added support for staking for subnets but that's also happen on the P-Chain (not on subnet-evm). 
Currently the rewarding on subnet-evm is only possible with reward fees. You can either activate that on genesis or as a precompile. See:
https://docs.avax.network/subnets/customize-a-subnet#changing-fee-reward-mechanisms
https://docs.avax.network/subnets/customize-a-subnet#setting-a-custom-fee-recipient

**Comment by gatesyp** [comment]
Thanks @ceyonur . 

With Banff, do you know if there is currently a way to define a subnet's rewards formula for the staking happening on the P-Chain? 

Or currently, would it be using the same rewards code I linked above? Trying to understand the rewards flow for an Elastic Subnet

**Comment by ceyonur** [comment]
Yes they subject to the same calculation as P-chain staking. You can define your own subnet max staking through the `Transform Subnet TX`, see:
https://docs.avax.network/specs/platform-transaction-serialization#what-unsigned-transform-subnet-tx-contains

**Comment by gatesyp** [comment]
thanks @ceyonur 

in the same vein, are block proposers chosen via the same algorithm the P Chain uses? (creating a committee from stake weight, with a time window given for each member before moving to the next)

**Comment by ceyonur** [comment]
true. all snowman vms (including subnet-evm) uses snowman++.

**Comment by aaronbuchwald** [comment]
Thanks for asking @gatesyp . You can also check out @abi87 's PR to add more documentation for elastic subnets: https://github.com/ava-labs/avalanche-docs/pull/1189. It should be merged very soon.

Going to close this issue for now since Subnet-EVM cannot override the P-Chain's staking reward formula.

There are two other alternatives on Subnet-EVM:

- reward manager precompile to specify where to send rewards - either to a static address or allowing the block proposer to claim the fees: https://docs.avax.network/subnets/customize-a-subnet#changing-fee-reward-mechanisms
- Setting a custom fee recipient in the genesis: https://docs.avax.network/subnets/customize-a-subnet#setting-a-custom-fee-recipient

There are certainly other potential ways that the VM could play a larger role in deciding fees. One example, would be for the P-Chain to notify the VMs on a Subnet when a subnet validator finishes its validation period.

**Comment by ceyonur** [comment]
Closing this, feel free to reopen if you have any further questions @gatesyp
