### ISSUE TITLE
Stateful precompile tutorial setup error

### ISSUE THREAD

**Issue by kevinz917** [ava-labs/subnet-evm#483]
**Describe the bug**
Experienced 2 bugs by following the tutorial here:
https://docs.avax.network/subnets/hello-world-precompile-tutorial#step-0-generating-the-precompile

The first error happens through downloading the repo. It gives a "SSH permission not found" error
![image](https://user-images.githubusercontent.com/40219813/216677725-da6ee42f-10d0-4667-9414-e86b517ab2b9.png)

The second error shows after following this step
![image](https://user-images.githubusercontent.com/40219813/216677417-7c6a988f-6875-4314-acbb-0961f8844604.png)

Error logs
![image](https://user-images.githubusercontent.com/40219813/216677460-1b63c09e-bb7e-4407-b0fc-1ed624b7bddb.png)

**Operating System**
Macbook M1 on macOS Montery

**Additional context**

**Comment by aaronbuchwald** [comment]
Thanks for putting this up. This is a result of the CGO flags that must be set when using the blst library that is imported by AvalancheGo. When building subnet-evm, we need to set this flag to ensure that it builds correctly:

https://github.com/ava-labs/subnet-evm/blob/master/scripts/constants.sh#L44

If you're running into this error, you can fix it by setting this flag when running it.

```bash
CGO_CFLAGS="-O -D__BLST_PORTABLE__" go run ./cmd/precompilegen/main.go <rest of the flags here>
```

We will work on fixing this so that you don't need to populate a variable like this in order to get it to work.

**Comment by aaronbuchwald** [comment]
Hey Kevin, I made a PR to create a new script so that you do not need to set the `CGO_FLAGS` manually.

The subnet-evm PR to add the new script is here: https://github.com/ava-labs/subnet-evm/pull/489 and there is an accompanying docs PR that updates the PrecompileGen tutorial here if you want to take a look: https://github.com/ava-labs/avalanche-docs/pull/1196.

Our docs repo auto-generates a preview URL, so you can check out the relevant changed docs here: https://7dda7439.avalanche-docs.pages.dev/subnets/hello-world-precompile-tutorial#step-0-generating-the-precompile. To test it, you will just need to checkout the related branch of subnet-evm called `precompile-gen-script`.

So the first step would change to:

```bash
cd $GOPATH/src/github.com/ava-labs/subnet-evm
git checkout precompile-gen-script
git checkout -b hello-world-stateful-precompile
```

Please let me know if this fixes the issue for you.
