### ISSUE TITLE
Fee Proxy Stateful Precompile

### ISSUE THREAD

**Issue by patrick-ogrady** [ava-labs/subnet-evm#55]
Allow an address to pay fees on the behalf of another address. This should be implemented as a precompile that allows any address to "claim a dependent" to pay for. It is unclear what should happen if a single address is claimed by multiple sponsors.

**Comment by aaronbuchwald** [comment]
One potential design for this would be to create a precompile that enforces a predicate by running a small computation that checks what (if any) gas should be afforded to a specific transaction (and either create that gas from nowhere or pay for it from its own balance).

This would be similar to how GSN pays fees for transactions via meta-transactions, except instead of executing a transaction on behalf of a user by using a trusted forwarder (https://eips.ethereum.org/EIPS/eip-2771) it would take care of it directly within subnet-evm by pulling that gas from a trusted contract and running a small pre-verification to see how much gas should be allotted to that transaction's execution. This way the actual signer of the transaction, would in fact be the intended `msg.sender`.

If we go this route, we should be aware of the potential DoS vectors associated with allowing a pre-verification step to invalidate a transaction: https://ethresear.ch/t/dos-vectors-in-account-abstraction-aa-or-validation-generalization-a-case-study-in-geth/7937.

This may provide a better experience in getting a subnet up and running that does not require setting up a GSN or similar on that subnet and instead placing that burden on the subnet operator. Before pursuing this, we should make sure that subnet operators would prefer this model.

**Comment by friskyfoxdk** [comment]
Lots of cool ideas here, subscribing

**Comment by aaronbuchwald** [comment]
Closing because we have decided not to pursue this as a precompile for now.
