### ISSUE TITLE
Deploying a wrapper contract around an allowlist fails even when the tx.origin should have permission

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/subnet-evm#630]
**Describe the bug**

If [this function](https://github.com/ava-labs/subnet-evm/blob/e38d39d9f1f9cc2e1b1c2cf8dec662e0830e82d6/contract-examples/contracts/ExampleDeployerList.sol#L65) is called by an admin (allowed to deploy contracts), the `try` block will succeed and [this line](https://github.com/ava-labs/subnet-evm/blob/e38d39d9f1f9cc2e1b1c2cf8dec662e0830e82d6/contract-examples/contracts/ExampleDeployerList.sol#L71) will get hit. 

If however, I change [this line](https://github.com/ava-labs/subnet-evm/blob/e38d39d9f1f9cc2e1b1c2cf8dec662e0830e82d6/contract-examples/contracts/ExampleDeployerList.sol#L19) such that it deploys an [`AllowList`](https://github.com/ava-labs/subnet-evm/blob/e38d39d9f1f9cc2e1b1c2cf8dec662e0830e82d6/contract-examples/contracts/ExampleDeployerList.sol#L6), then an error will be thrown in the `try` block.

I need to investigate why in the actual EVM code as there is no meaningful error message provided. 

**To Reproduce**
TBD

**Expected behavior**
both deployed contracts should succeed if an admin signs the original tx

**Screenshots**
N/A

**Logs**
N/A
**Metrics**
N/A

**Operating System**
N/A

**Additional context**
N/A

**Comment by aaronbuchwald** [comment]
Breaking this down for myself here:

The test code in question is:

```
  function test_noRoleCannotDeploy() public {
    IAllowList allowList = IAllowList(DEPLOYER_LIST);

    assertEq(allowList.readAllowList(tx.origin), 0);

    try example.deployContract() {
      assertTrue(false, "deployContract should fail");
    } catch {} // TODO should match on an error to make sure that this is failing in the way that's expected
  }
```

There are two cases here, if the code is called by an allowed/admin address or a disabled address ie. 0.

Since the test asserts `allowList.readAllowList(tx.origin) == 0`, this test will only pass if `tx.origin` is disabled. So the case that you've mentioned where an admin is `tx.origin` and the test makes it to the try block should never happen.

If `tx.origin` is disabled, then `example.deployContract()` should fail triggering the catch block and pass.

We've fixed this in the current test code here: https://github.com/ava-labs/subnet-evm/blob/ba46d7b48ac5b18ffd29140e5f4000fd1edb0c68/contracts/contracts/test/ExampleDeployerListTest.sol#L49 which I've verified is passing correctly in CI and have also verified the behavior of deploying a contract from an enabled/disabled address behaves as expected manually.

Checking out the permalinked code locally and running the contract deployer precompile test as is (where this test is called by `OTHER_SIGNER` which is a non-admin), the test passes.

Modifying the test so that it's called by the default pre-funded address (which is an admin):

```
test("should not let test address deploy", "test_noRoleCannotDeploy")
```

I see the following output:

```
Error: a == b not satisfied [uint]
      Left
BigNumber { value: "2" }
     Right
BigNumber { value: "0" }
Error
deployContract should fail
Error: Assertion Failed

    1) should not let test address deploy
```

It looks like the precondition for the test (it is called by a non-admin) fails first. After that, it hits the second error `deployContract should fail`. Since this is called by an admin, it's expected that it's able to deploy the contract.

Closing this as completed, since this was already fixed.
