### ISSUE TITLE
improve triedb metrics

### ISSUE THREAD

**Issue by darioush** [ava-labs/subnet-evm#651]
- Add metrics for the Cap function to increase observability as to when it is called and how much data it writes to disk.
Most of this data is likely not useful for nodes that are not archival, so measuring it can help size caches etc.
- Additionally it was observed that the dirty trie cache may be capping while the dirty trie cache metric shows a value below the threshold. We should check how the metric is calculated and the cache size is measured.

**Comment by najeal** [comment]
Assuming your are talking about the following metric (dirties_size) https://github.com/ava-labs/subnet-evm/blob/75c348610bfe282884fc96fd138e91f0b9fb9185/trie/database.go#L61
When calling Cap function, the calculated cache size to trigger or not the capping will be higher of the threshold before the metrics because it is `dirties_size + children_size + data_structs_size`
