### ISSUE TITLE
Testing utility for subnet feeConfig values

### ISSUE THREAD

**Issue by brandonaaskov** [ava-labs/subnet-evm#674]
**Context and scope**
Wen configuring a subnet, getting the fee config dialed in for a specific use case feels like trial-and-error. Thankfully that can happen with precompiles, but ideally there'd be a way to test that config to make sure the fees are sensible (e.g. low transaction fees, a slower ramp based on the `baseFeeChangeDenominator`, that the juice is worth the squeeze for validators, etc).

**Discussion and alternatives**
In [the most recent developer community call on YouTube](https://www.youtube.com/live/WR91UbQQRBI?feature=share&t=787), @patrick-ogrady starts talking about pricing the gas properly for AWM, and @aaronbuchwald mentioned the [contracts_test.go](https://github.com/ava-labs/subnet-evm/blob/master/core/vm/contracts_test.go) file that’s used to validate those precompiles. I'm not a Go developer, but I'm curious if this is something that can be leveraged already.

**Comment by aaronbuchwald** [comment]
If you take a look at one example of the precompile benchmarks here: https://github.com/ava-labs/subnet-evm/blob/master/core/vm/contracts_test.go#L205, you can run it and see that it reports a metric for the amount of gas processed per second.

The EVM charges for every operation that it performs intends to charge evenly for the amount of work that it does. Ie. if a sha256 hash costs N, performing it twice should cost 2n.

For pure compute operations, it's important to charge at least a roughly equal amount for two different operations that take a similar amount of time. This is because if there are two operations that take the same amount of time, but one of them is an order of magnitude cheaper, then if an attacker spams the less expensive operation it can slow down block processing time significantly, which creates a potential DoS vector.

Depending on the type of operation, there are different resources that gas is paying for. For example, sha256 will take some amount of CPU time, but does not impact state at all. In contrast, the EVM currently charges gas once for storing data in the state, which adds a long term cost to the network, so charging for state is VERY different than charging for pure compute time.

On that subject, here's a paper that you might be interested in: https://arxiv.org/abs/2208.07919

As for the question about defining a reasonable fee config. That is a different parameter than the gas cost itself.

Could you elaborate a bit more on your use case, what you are doing now, the issue that you're running into, and perhaps what the ideal experience would look like instead?

We do not have a ready to use simulation tool at the moment, but that's a great feature request.

**Comment by aaronbuchwald** [comment]
Thanks to @patrick-ogrady for recommending that paper btw, it's still on my reading list for the weekend, but thought I'd drop it because it seemed relevant to your question.

**Comment by aaronbuchwald** [comment]
Closing this issue as addressed, feel free to re-open if you have any further related questions

**Comment by brandonaaskov** [comment]
@aaronbuchwald can I get an example of _how_ to actual run this test? Again, I'm not a Go dev and even if I was, having instructions to actually be able to run the test is going to be a lot easier than me trying to figure it out as I go.

**Comment by aaronbuchwald** [comment]
These are no different than any other golang unit tests/benchmarks, so any tutorial will provide just as good if not better instructions than I could write up succinctly here. Here is one tutorial that I found helpful in the past: https://hackernoon.com/how-to-write-benchmarks-in-golang-like-an-expert-0w1834gs.

Unfortunately, they are not productized or made into a tool, so to use them as is you'd need to learn at least a bit of go.
