### ISSUE TITLE
Recommended # of validators and stake weight

### ISSUE THREAD

**Issue by atvanguard** [ava-labs/subnet-evm#690]
Collecting here some of the notes I gathered about subnet management from previous conversations

- Strong recommendation to have atleast 5 validators on a subnet but 7-8 is the minimum sweet spot.
- A subnet runs when atleast 80% of the validators by stake are up.

I wasn't able to figure out how the 2 statements above make sense in tandem. For e.g. say I have 5 validators with equal weight and if 1 goes down, then 80% of the network is still up and subnet continues to run. But how does the situation improve with 8 validators? Looks like even that can handle just 1 validator going down, because 6/8 = 75% < 80%. So looks like the situation only gets better with 10 validators? - I guess I am missing something here, maybe there is some specific play with stake weights that allows this to happen.

**Comment by atvanguard** [comment]
I spent some time reading the linked comment. I am not gifted at math so I have the following questions 😅 
1. What is the meaning of `k` (sample size) being 20 when there are only 8 other nodes.
2. Same for `alpha`.
3. Is it true that the numbers `0.0383514146` and `0.62362552658` refer to the probability of getting 15 consecutive successes? - If yes, what is the yardstick to say that a particular value indicates "block confirmation will slow down" or "confirmation will very likely to occur in a short period." If I try to simulate for 6000/8000, the value is `0.0007`, what should I infer from that?
4. Are the default values for alpha and k 15/20 or 18/25 as stated [here](https://docs.avax.network/nodes/maintain/subnet-configs).

**Comment by aaronbuchwald** [comment]
1. K is the sample size based off of stake, not the number of validators. The same validator can be selected multiple times, which would simply weight their response based off of how many times they are selected in the sample.
2. Same response for alpha.
3. Continued below
4. The default values for alpha and K are 15/20. The link you added is an example of how you could override the default parameters on a Subnet specific basis, not the defaults.

The wiki page for a hypergeometric distribution is pretty helpful here: https://en.wikipedia.org/wiki/Hypergeometric_distribution.

Given a population of size N, where exactly K objects in the population will result in a success, what is the probability of selecting k successes out of n draws (note that this definition of a hypergeometric series uses its own definition of k and n separate from the parameters for snow consensus). The hypergeometric distribution calculator here: https://stattrek.com/online-calculator/hypergeometric

![Screenshot 2023-06-23 at 11 33 11](https://github.com/ava-labs/subnet-evm/assets/24684335/a597f886-9250-4b03-9c1b-3e21d1e6f209)

gives the probability of = k successes, < k successes, <= k successes, > k successes, or >= k successes.

The case that we care about is >= k because this represents the chance that a single sub-sample of the network will see >= k successes.

In the Snow consensus case (switching back to the definitions of k and alpha from snow), this equates to the following:

1. The population N is the total stake of the network
2. The number of successes in the population is the amount of stake responding positively for our preference (eg we assume all nodes are voting for the same proposal and only offline nodes are voting differently/not responding in this example)
3. For each sub-sample, we sample 20 (k sample size) units of stake (this could result in an actual query to anywhere from 1-20 nodes), and if we receive >= 15 (alpha) votes in favor of the same proposal, then we increment our confidence

The hypergeometric distribution gives the probability that a single sub-sample will result in a successful poll where we receive >= alpha votes.

Finally, snow consensus requires beta (beta virtuous defaults to 15) consecutive polls in a row in order to accept a block. Therefore, if the hypergeometric distribution gives us a probability of getting >= 15/20 votes of 0.9, then we can take:

0.95^15 = 0.46 giving us a 46% chance that 15 consecutive polls will all result in success. This means that there is a 46% chance that a node will accept a block after the first 15 polls.

This gives a node about a 50% chance to terminate after the first 15 polls. AvalancheGo defaults to maintain 4 concurrent polls and pipelines votes (eg. a vote for block A can be applied transitively to all of its ancestors) and the latency of each poll is based off of how quickly each node can respond to queries, which is typically dominated by network latency.

For your result with 6000 successes out of a population of size 8000, this means that there would be a low probability that the network would finalize within the first 15 rounds of polling and would struggle to finalize with that portion of the network online.

**Comment by atvanguard** [comment]
Thank you @aaronbuchwald that helps a lot. So given the above information, we are thinking that if foundation runs 5 nodes with weight 900 each and some external partners run 3 validators with 300 weight each; then if all 3 external validators go down then is `0.89^15 = .17` enough to keep the network running (albeit with degraded performance)? Same scenario as 1 foundation node going down. Or do you suggest some other distribution?

<img width="507" alt="Screenshot 2023-06-26 at 4 11 13 PM" src="https://github.com/ava-labs/subnet-evm/assets/3612498/d1aa321a-8547-48dd-9f03-13f82c1a4a72">

**Comment by aaronbuchwald** [comment]
Your math looks correct to me 👍

Thanks for all of the great questions!
