### ISSUE TITLE
A non-validator is allowed to create blocks on a subnet

### ISSUE THREAD

**Issue by atvanguard** [ava-labs/subnet-evm#691]
Putting together the previous private conversation here to continue it:

**Q. if a validator is removed from a subnet, are they still allowed to propose block? even if they are proposed, is there any chance those blocks can be accepted in the chain?**

> 1. Yes, a non-validator is allowed to propose a block if the soft proposer window (30s) expires: https://github.com/ava-labs/avalanchego/blob/master/vms/proposervm/README.md
> 2. Yes after the soft proposer window expires, a block proposed by a non-validator is treated equally with others.
Changing this could be a reasonable feature request though

**Q. If a node can propose/accept block after it is removed as validator, how does removing the node as validator affect it ?**
> It’s vote has no weight in consensus if it is not a validator.

**Q. 1. what is the soft proposer window?
2. Can the block proposer who is not a validator also set the block fee recipient of their choice?**

> https://github.com/ava-labs/avalanchego/blob/master/vms/proposervm/README.md#congestion-control-mechanism-description
The ProposerVM wraps each VM in Avalanche, Subnet-EVM sets the block fee recipient which is separate and defaults to burning all of the fees rather than allowing the validator to specify the address to send fees to. If you'd like to change the fee behavior, you can look at the reward manager precompile to make changes: https://docs.avax.network/subnets/customize-a-subnet#changing-fee-reward-mechanisms

**Q. I meant that if the fees have already been configured to be sent to validators and not burn, then a field feeRecipient needs to be configured in the chain config, so as to know the fee destination. In that scenario and when a block by a non-validator is accepted, can the fee go to the non-validator address? (because they set the fee recipient to themselves)**
> Yes

**Q. How is that acceptable? fee going to people who are not validators in the system (unanswered)**

**Comment by atvanguard** [comment]
Now that I think about it it doesn't seem that bad that a non-validator could also produce blocks, given it can only happen after the soft proposer window. But also it's quite counter-intuitive to my view that a chain will go on even if all the validators are shut down. I do not have a strong opinion, but I guess it could be exposed as a configuration parameter where the subnet developer can opt-in for a particular behaviour.

**Comment by aaronbuchwald** [comment]
That's not currently supported.

What would the rationale be for adding a switch for validators to opt out of block building as opposed to adding a requirement to the verification rules (eg ProposerVM) that prevents non-validators from proposing blocks at all?

**Comment by atvanguard** [comment]
I thought this was a conscious design choice to let non-validators propose a block. Hence, I suggested having a switch. If it wasn't then preventing non-validators from proposing blocks all together is definitely better I feel.

> That's not currently supported.
The above refers to this correct? - is there a way to turn off block proposing attempts on a non-validator node - for e.g. our archival API node keeps trying to build a block.

**Comment by aaronbuchwald** [comment]
Ya allowing non-validators to propose a block is a result of ProposerVM opening up who is allowed to propose a block to ensure that if a few proposers are offline, eventually anyone can propose a block.

In the current design, this window expands for a period of 30s where the proposed block must include a signature from the validator that is proposing the block. After that 30s, it opens up to allow anyone to propose a block, so there is no requirement for a validator signature at that point.

We've discussed adding a validator signature even after that point even if anyone is allowed to propose a block, so that it's clear who proposed the block even after the proposer window has elapsed.

Once signatures are required for every block (even after the proposer window elapses), it should be fairly easy to add an option that requires that even after the proposer window has expired, the proposer must still be a validator of the network.

re: turning off block proposals

Ya, currently the VM will notify the ProposerVM that it is ready to propose a block when it has transactions to put in a block regardless of whether or not its a validator. The ProposerVM in turn wraps this notification and notifies the engine that its ready to propose a block when it is also its turn to propose.

This occurs here: https://github.com/ava-labs/subnet-evm/blob/master/plugin/evm/block_builder.go#L126 after the VM has received newly added transactions to its mempool either via the API or mempool gossip.

You could modify the VM to have a switch so that it never notifies the ProposerVM/engine its ready to build a block and in that case the engine will never call `BuildBlock` to try and propose a block.

Could you explain more why you consider it a problem for your archival API node to propose a block?

**Comment by atvanguard** [comment]
> Could you explain more why you consider it a problem for your archival API node to propose a block?
Since our modification to the subnet adds logic that requires to send some local txs as part of build block process, the API node keeps trying to do that which is as such not a problem just that we were just surprised to see this happens. Closing this now thank you.
