### ISSUE TITLE
block.timestamp in precompile

### ISSUE THREAD

**Issue by atvanguard** [ava-labs/subnet-evm#726]
This is a copy of the conversation that happened on a private channel b/w me, @aaronbuchwald and @ceyonur. On their request I am duplicating the conversation here, so that builders in the future can refer to it, if they run into the same issue.

---

_Q. What is the way to access block.timestamp in a precompile._
A. It’s part of the block context. I cant remember if it’s already exposed but think it is. If it’s not look at the timestamp opcode in the EVM and it should be pretty clear how to expose it to the precompile

_Q. blockContext has the timestamp of the last block_
A. It's the timestamp of the current block, not the parent. What leads you to think it's the parent?

Q.
```
t=2023-07-11T14:45:39.336+0100 lvl=info msg="#### received ChainAcceptedEvent"       number=15 hash=0x5f00d36f02034d51efba26a89d09f1d156d3a2ce269716416119e92774b03317 type=hubble caller=limit_order.go:201

t=2023-07-11T14:45:43.250+0100 lvl=info msg=ValidatePlaceIOCOrders                   GetBlockContext.Number=15 order.ExpireAt=1689083144 GetBlockContext.Timestamp=1689083139 ExpirationCap=5 timestamp=1689083143
```
_block 15 was accepted. Then in the next tx I am printing `accessibleState.GetBlockContext().Number()`
which is also 15. Hence last block. Also the timestamp `GetBlockContext().Timestamp()` is older than timestamp which is =time.Now().Unix()_

A. Can you share your code? the timestamp on the block should be the current block, but that is set by the block builder, so it will not be identical to time.Now().Unix() (depending on which node this is run on). It should be close though

_Q. yes doesn't need to be equal to time.Now().Unix() but I am certain it refers to last block - i confirmed with a block that was created 5 minutes ago_
A. I double checked this with one of our existing precompiles, and seems it reports the current block rather than the parent.
How do you call the precompile’s method? The validatePlaceIOCOrders seems like a view  function and it doesn’t actually produce any block once it’s directly called. So there is a possibility if you called this function directly (via RPC), it did not produce a new block and showed you the last block built like 5 mins ago.

_Q. I was looking at the log that was arising when ethers.js internally does estimateGas . so I sent in the gasLimit param now and see expected block number and timestamp. This is resolved now!_

**Comment by aaronbuchwald** [comment]
Thank you guys for diving into this and posting here for future reference! 🙌

**Comment by aaronbuchwald** [comment]
To add just a little bit more color, when you issue a transaction to the EVM and view the logs of a node there are a number of places that executing that transaction in the EVM will show up:

# APIs

## eth_estimateGas

https://github.com/ava-labs/subnet-evm/blob/v0.5.2/internal/ethapi/api.go#L1229

This API call is used to estimate the amount of gas that will be used by the transaction, so that users can set a conservative gas limit based on the expected execution path through the EVM. 

[DoEstimateGas](https://github.com/ava-labs/subnet-evm/blob/v0.5.2/internal/ethapi/api.go#L1107) will perform a bisection search for the lowest amount of gas that will result in the transaction executing successfully.

Note: if a transaction "fails" it can still be included in the block and charge the EOA account that issued it gas, it will just terminate with a failed transaction status. However, if this API call fails most libraries will see that failure and error before attempting to issue that transaction.

## eth_call

[DoCall](https://github.com/ava-labs/subnet-evm/blob/v0.5.2/internal/ethapi/api.go#L1095) will execute the call once to see what the result is and executes the transaction in the EVM.

# Block Building

The miner package is responsible for attempting to build a block and it will do so by serially executing transactions from the mempool here: https://github.com/ava-labs/subnet-evm/blob/v0.5.2/miner/worker.go#L290.

This will execute each transaction and make sure that it is valid to be included in the block. If the transaction fails, it will revert the state to the previous snapshot and start attempting to execute the next transaction.

This will execute each transaction it attempts to include through the EVM, which could also emit logs from your precompile if it's invoked.

# Block Verification

The consensus engine will verify the block after it's been built and other nodes that receive the block will verify it, so that for most nodes in the network it will only go through the verify execution path.

https://github.com/ava-labs/subnet-evm/blob/v0.5.2/plugin/evm/block.go#L171

Going to post this response here and on the other issue that you created: https://github.com/ava-labs/subnet-evm/issues/727
