### ISSUE TITLE
Unable to run a node for XANAChain subnet

### ISSUE THREAD

**Issue by SalmanNoborderz** [ava-labs/subnet-evm#740]
Describe the bug
Getting "Block failed verification during bootstrapping"

To Reproduce
Followed steps as mentioned in (https://docs.avax.network/nodes/build/run-avalanche-node-manually) and added --track-subnets=ii7zCu8JNnYYgPT8PwpVYiTS1gcK5RWJfsyuPXTDv8Bn9wspY

Expected behavior
It should be fully boostrapped with the the whitelisted subnet

Logs
[log.zip](https://github.com/ava-labs/coreth/files/12025110/log.zip)

Operating System
Ubuntu 18.04

**Comment by aaronbuchwald** [comment]
If you run Subnet-EVM on a subnet that has enabled network upgrades you have not applied on your node, then you may run into this issue.

Subnet-EVM supports performing a network upgrade by applying an `upgrade.json` file to the node, which specifies the activation timestamp and what upgrades should activate at that time. For more information about how this works, see here: https://docs.avax.network/subnets/customize-a-subnet#network-upgrades-enabledisable-precompiles.

We are working on this ticket: https://docs.avax.network/subnets/customize-a-subnet#network-upgrades-enabledisable-precompiles to provide support for a VM handshake, so that nodes know whether or not they have the same version of network upgrades applied: https://github.com/ava-labs/subnet-evm/issues/268.

Could you contact the XANA team to see if they have enabled any network upgrades? If so, you should follow the documentation linked above to apply the upgrade to your Subnet.

**Comment by SalmanNoborderz** [comment]
@aaronbuchwald  Yes that was the issue, thanks for the help!

**Comment by aaronbuchwald** [comment]
Thanks for confirming and glad that's resolved.

If they haven't already, I'd recommend asking them to put up a PR to this repo to include the `upgrade.json` necessary to run their network.
