### ISSUE TITLE
Title: Issue with tx.gasprice method in DFK Testnet

### ISSUE THREAD

**Issue by amit-supraoracles** [ava-labs/subnet-evm#756]
Hello Team,

I need help with the tx.gasprice method in REMIX IDE on DFK testnet.
The gas price returned seems incorrect or unavailable when deploying and executing a contract
```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.19;

contract GasConract {
    uint256 public gasPriceData;
    function setGasPrice() public {
        gasPriceData = tx.gasprice;
    }
}
```
Any insights or solutions would be appreciated.

Thank you,
Amit Kumar
[SupraOracles](https://supraoracles.com/)

**Comment by anusha-ctrl** [comment]
Hi,

**Comment by anusha-ctrl** [comment]
Please let me know if it works! Thanks

**Comment by amit-supraoracles** [comment]
Example : it normally takes 46k gas for the tx, but gas estimation was 23k,
this way it will fail.

**Comment by anusha-ctrl** [comment]
Ok, understood! Did you get it working?

**Comment by amit-supraoracles** [comment]
But I don't understand why metamask is not able to do estimation correctly.

**Comment by anusha-ctrl** [comment]
What error are you seeing?

**Comment by amit-supraoracles** [comment]
Let me share my wallet. I don't have laptop with me..rn

**Comment by amit-supraoracles** [comment]
0xde1C4cF6E992748cF56481da68e43627Bbc23cae

Please check in subnet testnet for failed tx

**Comment by amit-supraoracles** [comment]
I had same issue in bsc as well...might I didn't executed as it was failing.

Please check
https://testnet.bscscan.com/address/0xde1c4cf6e992748cf56481da68e43627bbc23cae

**Comment by anusha-ctrl** [comment]
These are failing due to an out of gas err. You might need to increase your gas limit.

**Comment by amit-supraoracles** [comment]
Yes..that's what I wanted to show that why metamask was unable to estimate
gas in this case correctly.

**Comment by aaronbuchwald** [comment]
Could you provide exact steps to reproduce? Since you're seeing the same error on BSC as well, this does not seem specific to Subnet-EVM.

That being said, it's not clear to me why serving `eth_estimateGas` would return an insufficient gas estimate.

One case could be that if the storage is modified between the estimate and actually issuing/executing the transaction on-chain the storage of the contract was modified such that the cost of an SSTORE operation changed (ie. charging more/less depending on if it's writing to a dirty or clean storage slot), but that doesn't appear to be the case from the transaction you shared.

**Comment by amit-supraoracles** [comment]
Thanks...let me share same once I start my day.

**Comment by amit-supraoracles** [comment]
Hey @aaronbuchwald @anusha-ctrl 
I just tried it again....everything is working fine.
Might it was temporary problem in metamask.

Thanks for support....
This issue can be closed right ?
