### ISSUE TITLE
Upgraded node v0.5.3 stuck

### ISSUE THREAD

**Issue by bsgrigorov** [ava-labs/subnet-evm#768]
**Describe the bug**
After restarting our DFK node because a new version of subnet evm v0.5.3 was released. And once the node was restarted it started creating a snapshot and the ETA just keeps increasing. Is there a way to disable this snapshot?
 <DFK Chain> github.com/ava-labs/subnet-evm/core/state/snapshot/generate.go:117: Generating state snapshot root=aa5b05..abd3ac in=1b70e3..54d8f1 at=937db0..3073c1 accounts=26286 slots=16,423,318 storage=1.10GiB    elapsed=9h24m41.718s eta=78h23m24.726s

Also the node is stuck on a block from a few hours ago and block height is not increasing.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Logs**
If applicable, please include the relevant logs that indicate a problem and/or the log directory of your node. By default, this can be found at `~/.avalanchego/logs/`.

**Metrics**
If applicable, please include any metrics gathered from your node to assist us in diagnosing the problem.

**Operating System**
Which OS you used to reveal the bug.

**Additional context**

Avalanche Bug Bounty program can be found [here](https://hackenproof.com/avalanche/avalanche-protocol).

**Comment by aaronbuchwald** [comment]
The snapshot is considered a requirement because it is a necessary performance improvement to create an O(1) lookup of the active state instead of requiring a lookup through the merkle trie.

Unfortunately, the snapshot can be corrupted during an unclean shutdown (although relatively unlikely). When running on very large states, it can be better to let the snapshot finish completely instead of trying to re-generate async while still processing blocks.

You may have better luck using setting the flag `--async-enabled=false` within the chain config for DFK to allow it to re-generate the snapshot and then move on to processing blocks.

If that gives a very large estimate, it may be easier to re-sync using state sync https://docs.avax.network/nodes/configure/chain-config-flags#state-sync-enabled-boolean.
