### ISSUE TITLE
`eth_blockNumber` returning 0 address instead of hex of latest block

### ISSUE THREAD

**Issue by meaghanfitzgerald** [ava-labs/subnet-evm#875]
**Describe the bug**
I am running an RPC node for a permissioned `Subnet-EVM` chain (deployed on fuji) and get an odd result when calling `eth_blockNumber` via curl. 

**To Reproduce**
```
curl --location 'http://localhost:9650/ext/bc/<BlockchainID>/rpc' --header 'Content-Type: application/json' --data '{
    "jsonrpc": "2.0",
    "method": "eth_blockNumber",
    "params": [],
    "id": 1
}'
```

Result:

``` 
{
    "jsonrpc":"2.0",
    "id":1,
    "result":"0x0"
}
```

more info on [this method](https://docs.alchemy.com/reference/eth-blocknumber-arbitrum)

**Expected behavior**

When called on C-chain:
```
curl --location 'http://localhost:9650/ext/bc/C/rpc' --header 'Content-Type: application/json' --data '{
    "jsonrpc": "2.0",
    "method": "eth_blockNumber",
    "params": [],
    "id": 1
}'
```

result is the hex representation of the latest blockheight:

```
{
  "jsonrpc": "2.0",    
  "id": 1,    
  "result": "0x18ca085"
}
```

**Operating System**
ubuntu - aws ec2 instance

**Comment by aaronbuchwald** [comment]
Why is this odd? It looks like the height on the Subnet is 0, is that the part that's unexpected?

**Comment by meaghanfitzgerald** [comment]
current height is 11,927

**Comment by aaronbuchwald** [comment]
Debugging offline, it looks like this subnet has no remaining validators.

If a subnet has 0 validators, then any new node that tries to bootstrap it will find that there are no validators to bootstrap from and end up with an empty network, which results in returning a latest height of 0.

Closing this issue, since it's not a problem with Subnet-EVM.
